name: Terraform Deployment

on:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    terraform:
        name: 'Terraform Apply'
        runs-on: ubuntu-latest
        env:
            DESTROY: ${{ secrets.DESTROY }}

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3
            
            - name: Setup AWS CLI
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: 'eu-north-1'

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                  terraform_version: 1.6.6

            - name: Terraform Init
              working-directory: terraform
              run: terraform init
            
            - name: Terraform validate
              working-directory: terraform
              run: terraform validate
            
            - name: Terraform Plan
              working-directory: terraform
              run: terraform plan -var-file="dev.tfvars"

            - name: Terraform Apply
              working-directory: terraform
              run: terraform apply -var-file="dev.tfvars" -auto-approve
           
            - name: Get EC2 IP
              id: tfoutput
              working-directory: terraform
              run: |
                echo "IP=$(terraform output -raw instance_public_ip)" >> $GITHUB_ENV

              # ------------------------
              # Setup SSH
              # ------------------------
            - name: Setup SSH Key
              run: |
                mkdir -p ~/.ssh
                echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/key.pem
                chmod 600 ~/.ssh/key.pem

            # ------------------------
            # Install Ansible
            # ------------------------
            - name: Install Ansible
              run: sudo apt install ansible -y

            - name: Install CIS Roles
              working-directory: ansible
              run: ansible-galaxy install -r requirements.yml

            # ------------------------
            # Run CIS Hardening
            # ------------------------
            - name: Run Hardening
              working-directory: ansible
              run: |
                echo "[servers]" > inventory.ini
                echo "$IP ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/key.pem" >> inventory.ini
                ansible-playbook -i inventory.ini site.yml

            # ------------------------
            # Install OpenSCAP on EC2
            # ------------------------
            - name: Install OpenSCAP
              run: |
                ssh -i ~/.ssh/key.pem ubuntu@$IP \
                "sudo apt update && sudo apt install openscap-scanner -y"

            # ------------------------
            # Run Compliance Scan
            # ------------------------
            - name: Run CIS Scan
              run: |
                ssh -i ~/.ssh/key.pem ubuntu@$IP \
                "sudo oscap xccdf eval \
                --profile xccdf_org.ssgproject.content_profile_cis \
                --results result.xml \
                /usr/share/xml/scap/ssg/content/ssg-ubuntu2004-ds.xml"

            # ------------------------
            # Upload Report
            # ------------------------
            - name: Fetch Report
              run: scp -i ~/.ssh/key.pem ubuntu@$IP:result.xml .

            - name: Upload Artifact
              uses: actions/upload-artifact@v3
              with:
                name: compliance-report
                path: result.xml
             
            - name: Terraform Destroy
              if: ${{ env.DESTROY == 'true' }}
              working-directory: terraform
              run: terraform destroy -var-file="dev.tfvars" -auto-approve
            